import pandas as pd
import numpy as np
from pathlib import Path
import re

# Paths
BASE_DIR = Path(__file__).resolve().parent.parent
RAW_DIR = BASE_DIR / "data" / "raw"
PROCESSED_DIR = BASE_DIR / "data" / "processed"

def calculate_rsi(series, period=14):
    delta = series.diff()
    gain = delta.clip(lower=0)
    loss = (-delta).clip(lower=0)
    
    # Wilder's smoothing
    avg_gain = gain.ewm(alpha=1/period, min_periods=period, adjust=False).mean()
    avg_loss = loss.ewm(alpha=1/period, min_periods=period, adjust=False).mean()
    
    rs = avg_gain / (avg_loss + 1e-10)
    rsi = 100 - (100 / (1 + rs))
    return rsi

def calculate_macd(series):
    ema12 = series.ewm(span=12, adjust=False).mean()
    ema26 = series.ewm(span=26, adjust=False).mean()
    macd = ema12 - ema26
    signal = macd.ewm(span=9, adjust=False).mean()
    histogram = macd - signal
    return macd, signal, histogram

def process_file(file_path):
    # ==========================================
    # STAGE 1: UPSTREAM CLEANING
    # ==========================================
    # Read the raw file
    df = pd.read_csv(file_path, low_memory=False)
    if df.empty:
        raise ValueError("File is empty.")

    # 1. Strip leading/trailing whitespace from column headers
    df.columns = df.columns.str.strip()

    # 2. Identify and remove repeated header rows
    if "COMPANY ID" in df.columns:
        df = df[df["COMPANY ID"].astype(str).str.strip() != "COMPANY ID"]

    # 3. Convert TRADING DATE
    if "TRADING DATE" not in df.columns:
        raise ValueError("TRADING DATE column not found.")
    
    df["TRADING DATE"] = pd.to_datetime(df["TRADING DATE"], format="%d-%b-%y", errors="coerce")
    df = df.dropna(subset=["TRADING DATE"])

    # 4. Aggressively clean numeric string columns
    numeric_cols = [
        "PRICE HIGH (Rs.)", "PRICE LOW (Rs.)", "CLOSE PRICE (Rs.)", 
        "OPEN PRICE (Rs.)", "TRADE VOLUME (No.)", "SHARE VOLUME (No.)", "TURNOVER (Rs.)"
    ]
    
    for col in numeric_cols:
        if col in df.columns:
            # Strip formatting anomalies like thousands commas and quotation marks
            df[col] = df[col].astype(str).str.replace(r'[^\d\.]', '', regex=True)
            df[col] = pd.to_numeric(df[col], errors="coerce")

    # 5. Fill missing or empty volume and turnover values with 0
    for col in ["TRADE VOLUME (No.)", "SHARE VOLUME (No.)", "TURNOVER (Rs.)"]:
        if col in df.columns:
            df[col] = df[col].fillna(0)

    # 6. Sort strictly by TRADING DATE in ascending order
    df = df.sort_values("TRADING DATE").reset_index(drop=True)

    # ==========================================
    # STAGE 2: FEATURE ENGINEERING
    # ==========================================
    
    # Standardize column names to lowercase snake_case
    rename_mapping = {
        "COMPANY ID": "company_id",
        "MAIN TYPE": "main_type",
        "SUB TYPE": "sub_type",
        "SHORT NAME": "short_name",
        "TRADING DATE": "trading_date",
        "PRICE HIGH (Rs.)": "price_high",
        "PRICE LOW (Rs.)": "price_low",
        "CLOSE PRICE (Rs.)": "close_price",
        "OPEN PRICE (Rs.)": "open_price",
        "TRADE VOLUME (No.)": "trade_volume",
        "SHARE VOLUME (No.)": "share_volume",
        "TURNOVER (Rs.)": "turnover"
    }
    df = df.rename(columns=rename_mapping)
    df.columns = df.columns.str.lower().str.replace(' ', '_')

    close = df["close_price"]

    # 1. Returns
    df["return_1d"] = close.pct_change(1)
    df["return_5d"] = close.pct_change(5)
    df["return_20d"] = close.pct_change(20)

    # 2. Simple Moving Averages
    df["sma_10"] = close.rolling(10).mean()
    df["sma_20"] = close.rolling(20).mean()
    df["sma_50"] = close.rolling(50).mean()

    # 3. Ratios
    df["close_sma10_ratio"] = close / df["sma_10"]
    df["close_sma20_ratio"] = close / df["sma_20"]
    df["close_sma50_ratio"] = close / df["sma_50"]

    # 4. RSI
    df["rsi_14"] = calculate_rsi(close, 14)

    # 5. MACD
    df["macd"], df["macd_signal"], df["macd_histogram"] = calculate_macd(close)

    # 6. Volatility
    df["volatility_20"] = df["return_1d"].rolling(20).std()

    # 7. Ratios for Volume/Turnover
    share_vol_sma = df["share_volume"].rolling(20).mean()
    df["volume_ratio"] = (df["share_volume"] / share_vol_sma).fillna(1.0)
    # Replace infinite values generated by division by zero
    df["volume_ratio"] = df["volume_ratio"].replace([np.inf, -np.inf], 1.0)

    turnover_sma = df["turnover"].rolling(20).mean()
    df["turnover_ratio"] = (df["turnover"] / turnover_sma).fillna(1.0)
    df["turnover_ratio"] = df["turnover_ratio"].replace([np.inf, -np.inf], 1.0)

    trade_vol_sma = df["trade_volume"] if "trade_volume" not in df.columns else df["trade_volume"].rolling(20).mean()
    if "trade_volume" in df.columns:
        df["trade_volume_ratio"] = (df["trade_volume"] / trade_vol_sma).fillna(1.0)
        df["trade_volume_ratio"] = df["trade_volume_ratio"].replace([np.inf, -np.inf], 1.0)

    # =========================================================================
    # UPGRADED PHASE 3: TARGET VARIABLE CREATION
    # =========================================================================
    
    # CRITICAL: Ensure the individual stock data is sorted chronologically before shifting
    df = df.sort_values("trading_date").reset_index(drop=True)

    # 1. Create the Continuous Return Target (Regression: 30-day forward return)
    df["future_return_30"] = (df["close_price"].shift(-30) - df["close_price"]) / df["close_price"]

    # 2. Create the Binary Target Upgrade (Classification: Up=1, Down/Flat=0)
    df["target_up"] = (df["future_return_30"] > 0).astype(int)

    # 3. Clean up NaNs
    # Drops both feature warmup NaNs (like sma_50) and the final 30 trailing look-ahead NaNs.
    df.dropna(
        subset=[
            "close_price", 
            "sma_50", 
            "return_20d", 
            "rsi_14", 
            "macd", 
            "future_return_30"
        ], 
        inplace=True
    )

    return df

def main():
    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
    csv_files = list(RAW_DIR.glob("*.csv"))
    
    if not csv_files:
        print(f"No CSV files found in {RAW_DIR}")
        return

    print(f"Found {len(csv_files)} files. Starting pipeline...\n")

    for file_path in csv_files:
        try:
            print(f"Processing: {file_path.name}")
            processed_df = process_file(file_path)
            
            output_name = f"{file_path.stem}_features.csv"
            output_path = PROCESSED_DIR / output_name
            
            processed_df.to_csv(output_path, index=False)
            print(f"  -> Successfully saved {output_name} ({len(processed_df)} rows)")
        except Exception as e:
            print(f"  -> ERROR processing {file_path.name}: {e}")

if __name__ == "__main__":
    main()